# Sources — Go only
sonar.sources=.

# Exclude Python, deps, generated files, and caches
sonar.exclusions=**/*.py,**/node_modules/**,**/__pycache__/**,**/vendor/**,clashy.go/**

# Go
sonar.go.coverage.reportPaths=coverage.out

# Tests
sonar.tests=.
sonar.test.inclusions=**/*_test.go
