# Sources — Go only
sonar.sources=.

# Exclude dependencies and generated files
sonar.exclusions=**/vendor/**,clashy.go/**,**/*.json

# Go
sonar.go.coverage.reportPaths=coverage.out

# Disable SCM blame (speeds up scan)
sonar.scm.disabled=true

# Tests
sonar.tests=.
sonar.test.inclusions=**/*_test.go
