import { botAdjacentEndpoints } from "./bot-adjacent.js"
import {
  BotClanCachedEndpoint,
  BotClanCapitalLeaderboardEndpoint,
  BotClanDonationsLeaderboardEndpoint,
  BotClanHistoryEndpoint,
  BotClanJoinLeaveEndpoint,
  BotClanLegendSummaryEndpoint,
  BotClanRankingsEndpoint,
  BotClanRecordsEndpoint,
  BotClanWarLogEndpoint,
  BotClanWarsEndpoint,
  BotClanWarWinsLeaderboardEndpoint,
  BotClanWinStreakLeaderboardEndpoint,
  BotCountsEndpoint,
  BotCurrentWarEndpoint,
  BotCwlGroupEndpoint,
  BotCwlLeaderboardEndpoint,
  BotCwlRankingHistoryEndpoint,
  BotCwlSeasonsEndpoint,
  BotLeagueLeaderboardEndpoint,
  BotLegendSeasonEndpoint,
  BotPlayerCwlHistoryEndpoint,
  BotPlayerHistoryEndpoint,
  BotPlayerLegendHistoryEndpoint,
  BotPlayerRankingsEndpoint,
  BotPlayerTimersEndpoint,
  BotPlayerWarAttacksEndpoint,
  BotPlayerWarStatsEndpoint,
  BotPreviousWarEndpoint,
  BotTownHallLeaderboardEndpoint,
} from "./bot-public.js"
import {
  BotAccountsEndpoint,
  BotAddStrikeEndpoint,
  BotBaseEndpoint,
  BotBasesEndpoint,
  BotBansEndpoint,
  BotDashboardCapabilitiesEndpoint,
  BotDeleteBanEndpoint,
  BotDeleteStrikeEndpoint,
  BotEmbedsEndpoint,
  BotGiveawayEndpoint,
  BotGiveawaysEndpoint,
  BotLinkAccountEndpoint,
  BotRefreshRosterEndpoint,
  BotRemindersEndpoint,
  BotRerollGiveawayEndpoint,
  BotRosterEndpoint,
  BotRostersEndpoint,
  BotSaveBanEndpoint,
  BotServerClanGamesLeaderboardEndpoint,
  BotServerClansEndpoint,
  BotServerDonationsLeaderboardEndpoint,
  BotServerLegendsLeaderboardEndpoint,
  BotServerLinksEndpoint,
  BotServerWarLeaderboardEndpoint,
  BotStrikeSummaryEndpoint,
  BotStrikesEndpoint,
  BotTicketsEndpoint,
  BotUnlinkAccountEndpoint,
} from "./bot-server.js"

export * from "./bot-public.js"
export * from "./bot-server.js"
export * from "./bot-adjacent.js"

// Only established API operations belong here. Deferred Discord orchestration
// schemas are available explicitly from the reference-only /deferred-runtime entry.
export const botEndpoints = {
  ...botAdjacentEndpoints,
  accounts: BotAccountsEndpoint,
  addStrike: BotAddStrikeEndpoint,
  base: BotBaseEndpoint,
  bases: BotBasesEndpoint,
  bans: BotBansEndpoint,
  clanCached: BotClanCachedEndpoint,
  clanCapitalLeaderboard: BotClanCapitalLeaderboardEndpoint,
  clanDonationsLeaderboard: BotClanDonationsLeaderboardEndpoint,
  clanHistory: BotClanHistoryEndpoint,
  clanJoinLeave: BotClanJoinLeaveEndpoint,
  clanLegendSummary: BotClanLegendSummaryEndpoint,
  clanRankings: BotClanRankingsEndpoint,
  clanRecords: BotClanRecordsEndpoint,
  clanWarLog: BotClanWarLogEndpoint,
  clanWars: BotClanWarsEndpoint,
  clanWarWinsLeaderboard: BotClanWarWinsLeaderboardEndpoint,
  clanWinStreakLeaderboard: BotClanWinStreakLeaderboardEndpoint,
  counts: BotCountsEndpoint,
  currentWar: BotCurrentWarEndpoint,
  cwlGroup: BotCwlGroupEndpoint,
  cwlLeaderboard: BotCwlLeaderboardEndpoint,
  cwlRankingHistory: BotCwlRankingHistoryEndpoint,
  cwlSeasons: BotCwlSeasonsEndpoint,
  dashboardCapabilities: BotDashboardCapabilitiesEndpoint,
  deleteBan: BotDeleteBanEndpoint,
  deleteStrike: BotDeleteStrikeEndpoint,
  embeds: BotEmbedsEndpoint,
  giveaway: BotGiveawayEndpoint,
  giveaways: BotGiveawaysEndpoint,
  leagueLeaderboard: BotLeagueLeaderboardEndpoint,
  legendSeason: BotLegendSeasonEndpoint,
  linkAccount: BotLinkAccountEndpoint,
  playerCwlHistory: BotPlayerCwlHistoryEndpoint,
  playerHistory: BotPlayerHistoryEndpoint,
  playerLegendHistory: BotPlayerLegendHistoryEndpoint,
  playerRankings: BotPlayerRankingsEndpoint,
  playerTimers: BotPlayerTimersEndpoint,
  playerWarAttacks: BotPlayerWarAttacksEndpoint,
  playerWarStats: BotPlayerWarStatsEndpoint,
  previousWar: BotPreviousWarEndpoint,
  refreshRoster: BotRefreshRosterEndpoint,
  reminders: BotRemindersEndpoint,
  rerollGiveaway: BotRerollGiveawayEndpoint,
  roster: BotRosterEndpoint,
  rosters: BotRostersEndpoint,
  saveBan: BotSaveBanEndpoint,
  serverClanGamesLeaderboard: BotServerClanGamesLeaderboardEndpoint,
  serverClans: BotServerClansEndpoint,
  serverDonationsLeaderboard: BotServerDonationsLeaderboardEndpoint,
  serverLegendsLeaderboard: BotServerLegendsLeaderboardEndpoint,
  serverLinks: BotServerLinksEndpoint,
  serverWarLeaderboard: BotServerWarLeaderboardEndpoint,
  strikeSummary: BotStrikeSummaryEndpoint,
  strikes: BotStrikesEndpoint,
  tickets: BotTicketsEndpoint,
  townHallLeaderboard: BotTownHallLeaderboardEndpoint,
  unlinkAccount: BotUnlinkAccountEndpoint,
} as const
