import { Schema } from "effect"
import { defineEndpoint, NoBody, NoQuery } from "./endpoint.js"
import { ErrorResponse } from "./errors.js"
import { BadgeUrls, ClanTagPath, HistoryQuery, JsonValue } from "./expo-common.js"
import { WarResponse } from "./expo-war.js"

const NotFound = [{ status: 404, body: ErrorResponse }] as const
const BadRequest = [{ status: 400, body: ErrorResponse }] as const
const LeagueReference = Schema.Struct({ id: Schema.Number, name: Schema.String })
const CwlRounds = Schema.Struct({ won: Schema.Number, tied: Schema.Number, lost: Schema.Number })
export const ClanCwlSeasonsResponse = Schema.Struct({ items: Schema.Array(Schema.Struct({ season: Schema.String, state: Schema.String, warSize: Schema.NullOr(Schema.Number), warLeague: Schema.NullOr(LeagueReference), rank: Schema.NullOr(Schema.Number), stars: Schema.NullOr(Schema.Number), destruction: Schema.NullOr(Schema.Number), rounds: Schema.NullOr(CwlRounds) })) })
const Location = Schema.Struct({ id: Schema.Number, name: Schema.optionalKey(Schema.String), isCountry: Schema.Boolean, countryCode: Schema.optionalKey(Schema.String), localizedName: Schema.optionalKey(Schema.String) })
export const ClanLeaderboardHistoryResponse = Schema.Struct({ items: Schema.Array(Schema.Struct({ date: Schema.String, rank: Schema.Number, clanPoints: Schema.optionalKey(Schema.Number), builderBasePoints: Schema.optionalKey(Schema.Number), capitalPoints: Schema.optionalKey(Schema.Number), members: Schema.Number, location: Schema.optionalKey(Location) })) })
export const ClanLeaderboardSummaryResponse = Schema.Struct({ seasons: Schema.Array(Schema.Struct({ season: Schema.String, after: Schema.String, before: Schema.String, daysInTop200: Schema.Number, bestRank: Schema.Number, peakPoints: Schema.Number })) })
export const ClanLegendHistoryResponse = Schema.Struct({ items: Schema.Array(Schema.Struct({ season: Schema.String, tag: Schema.String, name: Schema.String, trophies: Schema.Number, attackWins: Schema.Number, defenseWins: Schema.Number, rank: Schema.Number })) })
export const ClanLegendSummaryResponse = Schema.Struct({
  seasons: Schema.Array(Schema.Struct({ season: Schema.String, after: Schema.String, before: Schema.String, playerCount: Schema.Number })),
  topFinishes: Schema.Array(Schema.Struct({ season: Schema.String, tag: Schema.String, name: Schema.String, trophies: Schema.Number, attackWins: Schema.Number, defenseWins: Schema.Number, rank: Schema.Number })),
})
const RecordEntry = Schema.Struct({ value: Schema.Number, time: Schema.String })
export const ClanRecordsResponse = Schema.Struct({ clanPoints: Schema.optionalKey(RecordEntry), warWinStreak: Schema.optionalKey(RecordEntry) })
export const ClanChangesResponse = Schema.Struct({ items: Schema.Array(Schema.Struct({ time: Schema.String, type: Schema.String, previous: JsonValue, current: JsonValue })) })
const WarLogSide = Schema.Struct({ tag: Schema.String, name: Schema.String, badgeUrls: BadgeUrls, clanLevel: Schema.Number, attacks: Schema.Number, stars: Schema.Number, destructionPercentage: Schema.Number })
export const ClanWarlogResponse = Schema.Struct({ items: Schema.Array(Schema.Struct({ result: Schema.Literals(["win", "lose", "tie"]), type: Schema.Literals(["cwl", "random", "friendly"]), endTime: Schema.String, teamSize: Schema.Number, attacksPerMember: Schema.Number, clan: WarLogSide, opponent: WarLogSide })) })
export const ClanWarsResponse = Schema.Struct({ items: Schema.Array(WarResponse) })
const JoinLeaveClan = Schema.Struct({ name: Schema.String, tag: Schema.String })
export const ClanJoinLeaveResponse = Schema.Struct({ items: Schema.Array(Schema.Struct({ time: Schema.String, type: Schema.String, tag: Schema.String, name: Schema.optionalKey(Schema.String), townHallLevel: Schema.optionalKey(Schema.Number), clan: Schema.optionalKey(JoinLeaveClan) })), available: Schema.Number, uniquePlayers: Schema.optionalKey(Schema.Number) })

export const ClanCwlSeasonsEndpoint = defineEndpoint({ operationId: "getExpoClanCwlSeasons", method: "GET", path: "/v2/cwl/:clanTag/seasons", auth: "public", summary: "Get clan CWL seasons", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: Schema.Struct({ limit: Schema.optionalKey(Schema.Number) }), response: ClanCwlSeasonsResponse, responseMode: "json", successStatus: 200, errors: NotFound })
export const ClanLeaderboardHistoryEndpoint = defineEndpoint({ operationId: "getExpoClanLeaderboardHistory", method: "GET", path: "/v2/clan/:clanTag/history/leaderboards", auth: "public", summary: "Get clan leaderboard history", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: HistoryQuery, response: ClanLeaderboardHistoryResponse, responseMode: "json", successStatus: 200, errors: NotFound })
export const ClanLeaderboardSummaryEndpoint = defineEndpoint({ operationId: "getExpoClanLeaderboardSummary", method: "GET", path: "/v2/clan/:clanTag/history/leaderboards/summary", auth: "public", summary: "Get clan leaderboard history summary", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: Schema.Struct({ type: Schema.String }), response: ClanLeaderboardSummaryResponse, responseMode: "json", successStatus: 200, errors: NotFound })
export const ClanLegendHistoryEndpoint = defineEndpoint({ operationId: "getExpoClanLegendHistory", method: "GET", path: "/v2/clan/:clanTag/history/legends", auth: "public", summary: "Get clan legend history", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: Schema.Struct({ limit: Schema.optionalKey(Schema.Number), "time[after]": Schema.optionalKey(Schema.String), "time[before]": Schema.optionalKey(Schema.String) }), response: ClanLegendHistoryResponse, responseMode: "json", successStatus: 200, errors: NotFound })
export const ClanLegendSummaryEndpoint = defineEndpoint({ operationId: "getExpoClanLegendSummary", method: "GET", path: "/v2/clan/:clanTag/history/legends/summary", auth: "public", summary: "Get clan legend history summary", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: Schema.Struct({ top: Schema.optionalKey(Schema.Number) }), response: ClanLegendSummaryResponse, responseMode: "json", successStatus: 200, errors: NotFound })
export const ClanRecordsEndpoint = defineEndpoint({ operationId: "getExpoClanRecords", method: "GET", path: "/v2/clan/:clanTag/records", auth: "public", summary: "Get clan records", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: NoQuery, response: ClanRecordsResponse, responseMode: "json", successStatus: 200, errors: NotFound })
export const ClanChangesEndpoint = defineEndpoint({ operationId: "getExpoClanChanges", method: "GET", path: "/v2/clan/:clanTag/history/changes", auth: "public", summary: "Get clan change history", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: HistoryQuery, response: ClanChangesResponse, responseMode: "json", successStatus: 200, errors: NotFound })
export const ClanWarlogEndpoint = defineEndpoint({ operationId: "getExpoClanWarlog", method: "GET", path: "/v2/clan/:clanTag/warlog", auth: "user", summary: "Get a clan war log through ClashKing", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: HistoryQuery, response: ClanWarlogResponse, responseMode: "json", successStatus: 200, errors: BadRequest })
export const ClanWarsEndpoint = defineEndpoint({ operationId: "getExpoClanWars", method: "GET", path: "/v2/clan/:clanTag/wars", auth: "public", summary: "Get stored clan wars", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: HistoryQuery, response: ClanWarsResponse, responseMode: "json", successStatus: 200, errors: BadRequest })
export const ClanJoinLeaveEndpoint = defineEndpoint({ operationId: "getExpoClanJoinLeave", method: "GET", path: "/v2/clan/:clanTag/join-leave", auth: "user", summary: "Get clan join and leave history", body: NoBody, bodyMode: "none", pathParams: ClanTagPath, query: Schema.Struct({ limit: Schema.optionalKey(Schema.Number), "time[before]": Schema.optionalKey(Schema.String) }), response: ClanJoinLeaveResponse, responseMode: "json", successStatus: 200, errors: NotFound })
