import { AppConfigEndpoint } from "./app-config.js"
import { StoredCwlGroupEndpoint } from "./stored-cwl.js"
export { StoredCwlGroupEndpoint, StoredCwlGroupResponse } from "./stored-cwl.js"
import {
  AuthDeleteEndpoint,
  AuthDiscordEndpoint,
  AuthEmailEndpoint,
  AuthExportEndpoint,
  AuthForgotPasswordEndpoint,
  AuthMeEndpoint,
  AuthRefreshEndpoint,
  AuthRegisterEndpoint,
  AuthResendVerificationEndpoint,
  AuthResetPasswordEndpoint,
  AuthVerifyEmailEndpoint,
  AuthWebDiscordEndpoint,
  AuthWebEmailEndpoint,
  AuthWebLogoutEndpoint,
  AuthWebRefreshEndpoint,
  AuthWebResetPasswordEndpoint,
  AuthWebVerifyEmailEndpoint,
} from "./expo-auth.js"
import {
  ClanChangesEndpoint,
  ClanCwlSeasonsEndpoint,
  ClanJoinLeaveEndpoint,
  ClanLeaderboardHistoryEndpoint,
  ClanLeaderboardSummaryEndpoint,
  ClanLegendHistoryEndpoint,
  ClanLegendSummaryEndpoint,
  ClanRecordsEndpoint,
  ClanWarlogEndpoint,
  ClanWarsEndpoint,
} from "./expo-clan.js"
import {
  AchievementsCheckEndpoint,
  ActiveAnnouncementsEndpoint,
  AnnouncementEndpoint,
  AppUpdateManifestEndpoint,
  BillingSubscriptionEndpoint,
  PostsEndpoint,
} from "./expo-content.js"
import { CwlSummaryExportEndpoint, PlayerWarStatsExportEndpoint } from "./expo-exports.js"
import {
  BookmarksAddEndpoint,
  BookmarksDeleteEndpoint,
  BookmarksListEndpoint,
  BookmarksOrderEndpoint,
  LinksAddEndpoint,
  LinksListEndpoint,
  LinksOrderEndpoint,
  LinksRemoveEndpoint,
  LinksVisibilityEndpoint,
  RecentSearchesEndpoint,
  UpgradePreferencesGetEndpoint,
  UpgradePreferencesPatchEndpoint,
  UpgradesGetEndpoint,
  UpgradesPutEndpoint,
} from "./expo-links.js"
import {
  NotificationAccountPutEndpoint,
  NotificationDeviceDeleteEndpoint,
  NotificationDeviceRegisterEndpoint,
  NotificationPreferencesGetEndpoint,
  NotificationPreferencesPutEndpoint,
} from "./expo-notifications.js"
import {
  PlayerBattlelogHistoryEndpoint,
  PlayerChangesEndpoint,
  PlayerCwlHistoryEndpoint,
  PlayerJoinLeaveEndpoint,
  PlayerJoinLeaveTotalsEndpoint,
  PlayerSearchEndpoint,
  PlayerTimersEndpoint,
  PlayerWarStatsEndpoint,
} from "./expo-player.js"
import {
  LeaderboardClanDonationsEndpoint,
  LeaderboardClanWarWinsEndpoint,
  LeaderboardClanWinStreakEndpoint,
  LeaderboardHistoryEndpoint,
  LeaderboardLeagueEndpoint,
  LeaderboardTownhallsEndpoint,
} from "./expo-rankings.js"
import {
  ClanCapitalLeagueCountsEndpoint,
  ClanLocationCountsEndpoint,
  CwlLeagueCountsEndpoint,
  GlobalCountsEndpoint,
  PlayerBuilderhallCountsEndpoint,
  PlayerLeagueTierCountsEndpoint,
  PlayerTownhallCountsEndpoint,
} from "./expo-stats.js"
import { WarBasicEndpoint, WarPreviousEndpoint } from "./expo-war.js"
import {
  ProxyBuilderClanRankingsEndpoint,
  ProxyBuilderPlayerRankingsEndpoint,
  ProxyCapitalRaidSeasonsEndpoint,
  ProxyCapitalRankingsEndpoint,
  ProxyClanEndpoint,
  ProxyClanRankingsEndpoint,
  ProxyClanSearchEndpoint,
  ProxyClanWarlogEndpoint,
  ProxyCurrentLeagueGroupEndpoint,
  ProxyCurrentWarEndpoint,
  ProxyCwlWarEndpoint,
  ProxyLeagueGroupEndpoint,
  ProxyLeagueTiersEndpoint,
  ProxyLocationsEndpoint,
  ProxyPlayerBattlelogEndpoint,
  ProxyPlayerEndpoint,
  ProxyPlayerLeagueHistoryEndpoint,
  ProxyPlayerRankingsEndpoint,
} from "./proxy.js"
import {
  StatsCwlEndpoint,
  StatsRankedEndpoint,
  StatsWarEndpoint,
} from "./stats.js"
import { leagueAnalyticsEndpoints } from "./league-analytics.js"
import { statsHistoryEndpoints } from "./stats-history.js"

export * from "./expo-auth.js"
export * from "./expo-clan.js"
export * from "./expo-content.js"
export * from "./expo-exports.js"
export * from "./expo-links.js"
export * from "./expo-notifications.js"
export * from "./expo-player.js"
export * from "./expo-rankings.js"
export * from "./expo-stats.js"
export * from "./expo-war.js"
export * from "./league-analytics.js"
export * from "./stats-history.js"
export * from "./proxy.js"
export { AppConfigEndpoint, AppConfigResponse } from "./app-config.js"
export type { AnyEndpoint, EndpointRequest, EndpointResponse } from "./endpoint.js"
export { StatsCwlEndpoint, StatsCwlQuery,
  StatsRankedEndpoint, StatsRankedQuery,
  StatsWarEndpoint, StatsWarQuery } from "./stats.js"

export const expoEndpoints = {
  ...leagueAnalyticsEndpoints,
  ...statsHistoryEndpoints,
  storedCwlGroup: StoredCwlGroupEndpoint,
  appConfig: AppConfigEndpoint,
  authMe: AuthMeEndpoint,
  authDiscord: AuthDiscordEndpoint,
  authWebDiscord: AuthWebDiscordEndpoint,
  authEmail: AuthEmailEndpoint,
  authWebEmail: AuthWebEmailEndpoint,
  authRegister: AuthRegisterEndpoint,
  authVerifyEmail: AuthVerifyEmailEndpoint,
  authWebVerifyEmail: AuthWebVerifyEmailEndpoint,
  authResendVerification: AuthResendVerificationEndpoint,
  authForgotPassword: AuthForgotPasswordEndpoint,
  authResetPassword: AuthResetPasswordEndpoint,
  authWebResetPassword: AuthWebResetPasswordEndpoint,
  authRefresh: AuthRefreshEndpoint,
  authWebRefresh: AuthWebRefreshEndpoint,
  authExport: AuthExportEndpoint,
  authDelete: AuthDeleteEndpoint,
  authWebLogout: AuthWebLogoutEndpoint,
  linksList: LinksListEndpoint,
  linksAdd: LinksAddEndpoint,
  linksRemove: LinksRemoveEndpoint,
  linksVisibility: LinksVisibilityEndpoint,
  linksOrder: LinksOrderEndpoint,
  bookmarksList: BookmarksListEndpoint,
  bookmarksAdd: BookmarksAddEndpoint,
  bookmarksDelete: BookmarksDeleteEndpoint,
  bookmarksOrder: BookmarksOrderEndpoint,
  recentSearches: RecentSearchesEndpoint,
  upgradesGet: UpgradesGetEndpoint,
  upgradesPut: UpgradesPutEndpoint,
  upgradePreferencesGet: UpgradePreferencesGetEndpoint,
  upgradePreferencesPatch: UpgradePreferencesPatchEndpoint,
  playerSearch: PlayerSearchEndpoint,
  playerBattlelogHistory: PlayerBattlelogHistoryEndpoint,
  playerChanges: PlayerChangesEndpoint,
  playerCwlHistory: PlayerCwlHistoryEndpoint,
  playerTimers: PlayerTimersEndpoint,
  playerJoinLeave: PlayerJoinLeaveEndpoint,
  playerJoinLeaveTotals: PlayerJoinLeaveTotalsEndpoint,
  playerWarStats: PlayerWarStatsEndpoint,
  clanCwlSeasons: ClanCwlSeasonsEndpoint,
  clanLeaderboardHistory: ClanLeaderboardHistoryEndpoint,
  clanLeaderboardSummary: ClanLeaderboardSummaryEndpoint,
  clanLegendHistory: ClanLegendHistoryEndpoint,
  clanLegendSummary: ClanLegendSummaryEndpoint,
  clanRecords: ClanRecordsEndpoint,
  clanChanges: ClanChangesEndpoint,
  clanWarlog: ClanWarlogEndpoint,
  clanWars: ClanWarsEndpoint,
  clanJoinLeave: ClanJoinLeaveEndpoint,
  warBasic: WarBasicEndpoint,
  warPrevious: WarPreviousEndpoint,
  leaderboardHistory: LeaderboardHistoryEndpoint,
  leaderboardTownhalls: LeaderboardTownhallsEndpoint,
  leaderboardLeague: LeaderboardLeagueEndpoint,
  leaderboardClanDonations: LeaderboardClanDonationsEndpoint,
  leaderboardClanWarWins: LeaderboardClanWarWinsEndpoint,
  leaderboardClanWinStreak: LeaderboardClanWinStreakEndpoint,
  notificationDeviceRegister: NotificationDeviceRegisterEndpoint,
  notificationDeviceDelete: NotificationDeviceDeleteEndpoint,
  notificationPreferencesGet: NotificationPreferencesGetEndpoint,
  notificationPreferencesPut: NotificationPreferencesPutEndpoint,
  notificationAccountPut: NotificationAccountPutEndpoint,
  achievementsCheck: AchievementsCheckEndpoint,
  appUpdateManifest: AppUpdateManifestEndpoint,
  activeAnnouncements: ActiveAnnouncementsEndpoint,
  announcement: AnnouncementEndpoint,
  posts: PostsEndpoint,
  billingSubscription: BillingSubscriptionEndpoint,
  cwlSummaryExport: CwlSummaryExportEndpoint,
  playerWarStatsExport: PlayerWarStatsExportEndpoint,
  globalCounts: GlobalCountsEndpoint,
  playerTownhallCounts: PlayerTownhallCountsEndpoint,
  playerBuilderhallCounts: PlayerBuilderhallCountsEndpoint,
  playerLeagueTierCounts: PlayerLeagueTierCountsEndpoint,
  clanLocationCounts: ClanLocationCountsEndpoint,
  cwlLeagueCounts: CwlLeagueCountsEndpoint,
  clanCapitalLeagueCounts: ClanCapitalLeagueCountsEndpoint,
  statsRanked: StatsRankedEndpoint,
  statsWar: StatsWarEndpoint,
  statsCwl: StatsCwlEndpoint,
  proxyPlayer: ProxyPlayerEndpoint,
  proxyPlayerBattlelog: ProxyPlayerBattlelogEndpoint,
  proxyPlayerLeagueHistory: ProxyPlayerLeagueHistoryEndpoint,
  proxyLeagueGroup: ProxyLeagueGroupEndpoint,
  proxyLeagueTiers: ProxyLeagueTiersEndpoint,
  proxyClan: ProxyClanEndpoint,
  proxyClanSearch: ProxyClanSearchEndpoint,
  proxyCapitalRaidSeasons: ProxyCapitalRaidSeasonsEndpoint,
  proxyClanWarlog: ProxyClanWarlogEndpoint,
  proxyCurrentWar: ProxyCurrentWarEndpoint,
  proxyCurrentLeagueGroup: ProxyCurrentLeagueGroupEndpoint,
  proxyCwlWar: ProxyCwlWarEndpoint,
  proxyLocations: ProxyLocationsEndpoint,
  proxyPlayerRankings: ProxyPlayerRankingsEndpoint,
  proxyBuilderPlayerRankings: ProxyBuilderPlayerRankingsEndpoint,
  proxyClanRankings: ProxyClanRankingsEndpoint,
  proxyBuilderClanRankings: ProxyBuilderClanRankingsEndpoint,
  proxyCapitalRankings: ProxyCapitalRankingsEndpoint,
} as const
