package v2

import (
	serverroutes "github.com/ClashKingInc/ClashKingAPI/internal/routes/v2/server"
	apptypes "github.com/ClashKingInc/ClashKingAPI/internal/utils"
	"github.com/gofiber/fiber/v2"
)

func Register(app *fiber.App, a apptypes.Deps, wrap func(fiber.Handler) fiber.Handler) {
	app.Post("/v2/users/coc-accounts", wrap(addStandardAccount(a)))
	app.Post("/v2/users/coc-accounts/verified", wrap(addVerifiedAccount(a)))
	app.Get("/v2/users/coc-accounts", wrap(listAccounts(a)))
	app.Delete("/v2/users/coc-accounts/:player_tag", wrap(removeAccount(a)))
	app.Get("/v2/users/coc-accounts/:player_tag/status", wrap(accountStatus(a)))
	app.Put("/v2/users/coc-accounts/order", wrap(reorderAccounts(a)))
	app.Post("/v2/users/coc-accounts/:player_tag/verify", wrap(verifyAccount(a)))

	app.Get("/v2/guild-summary", guildSummary(a))
	app.Get("/v2/inactive-players", inactivePlayers(a))
	app.Get("/v2/activity/guild-summary", guildSummary(a))
	app.Get("/v2/activity/inactive-players", inactivePlayers(a))

	app.Post("/v2/verify-email-code", verifyEmailCode(a))
	app.Post("/v2/auth/verify-email-code", verifyEmailCode(a))
	app.Get("/v2/me", wrap(currentUser(a)))
	app.Get("/v2/auth/me", wrap(currentUser(a)))
	app.Post("/v2/discord", discordAuth(a))
	app.Post("/v2/auth/discord", discordAuth(a))
	app.Post("/v2/refresh", refreshToken(a))
	app.Post("/v2/auth/refresh", refreshToken(a))
	app.Post("/v2/register", register(a))
	app.Post("/v2/auth/register", register(a))
	app.Post("/v2/resend-verification", resendVerification(a))
	app.Post("/v2/auth/resend-verification", resendVerification(a))
	app.Post("/v2/email", emailLogin(a))
	app.Post("/v2/auth/email", emailLogin(a))
	app.Post("/v2/link-discord", wrap(linkDiscord(a)))
	app.Post("/v2/auth/link-discord", wrap(linkDiscord(a)))
	app.Post("/v2/link-email", wrap(linkEmail(a)))
	app.Post("/v2/auth/link-email", wrap(linkEmail(a)))
	app.Post("/v2/forgot-password", forgotPassword(a))
	app.Post("/v2/auth/forgot-password", forgotPassword(a))
	app.Post("/v2/reset-password", resetPassword(a))
	app.Post("/v2/auth/reset-password", resetPassword(a))

	app.Get("/v2/capital/player-stats", playerStats(a))
	app.Get("/v2/capital/guild-leaderboard", guildLeaderboard(a))

	app.Get("/v2/clan/:clan_tag/ranking", clanRanking(a))
	app.Get("/v2/clan/:clan_tag/board/totals", boardTotals(a))
	app.Get("/v2/clan/:clan_tag/donations/:season", clanDonationsSingle(a))
	app.Get("/v2/clan/:clan_tag/games/:season", clanGamesLeaderboard(a))
	app.Get("/v2/clan/:clan_tag/capital/latest", clanCapitalLatest(a))
	app.Get("/v2/clan/:clan_tag/war-opt", clanWarOpt(a))
	app.Get("/v2/clan/compo", clanComposition(a))
	app.Get("/v2/clan/donations/:season", clanDonationsMany(a))
	app.Post("/v2/clans/details", clansDetails(a))
	app.Get("/v2/clan/:clan_tag/details", clanDetails(a))
	app.Get("/v2/clan/:clan_tag/join-leave", clanJoinLeaveSingle(a))
	app.Post("/v2/clans/join-leave", clansJoinLeave(a))
	app.Post("/v2/clans/capital-raids", clansCapitalRaids(a))

	app.Get("/v2/public", publicConfig(a))
	app.Get("/v2/config/public", publicConfig(a))

	app.Get("/v2/dates/seasons", seasons)
	app.Get("/v2/dates/raid-weekends", raidWeekends)
	app.Get("/v2/dates/current", currentDates)
	app.Get("/v2/dates/season-start-end", seasonStartEnd)
	app.Get("/v2/dates/season-raid-dates", seasonRaidDates)

	app.Get("/v2/guilds", wrap(getUserGuilds(a)))
	app.Get("/v2/guild/:server_id", wrap(getGuildDetails(a)))

	app.Get("/v2/internal/bot/info", wrap(botInfo(a)))

	app.Post("/v2/tracking/players/add", wrap(addTrackingPlayers(a)))
	app.Post("/v2/tracking/players/remove", wrap(removeTrackingPlayers(a)))

	app.Get("/v2/search/clan", searchClan(a))
	app.Get("/v2/search/:guild_id/banned-players", wrap(searchBannedPlayers(a)))
	app.Post("/v2/search/bookmark/:user_id/:search_type/:tag", wrap(bookmarkSearch(a)))
	app.Post("/v2/search/recent/:user_id/:search_type/:tag", wrap(recentSearch(a)))
	app.Post("/v2/search/groups/create/:user_id/:name/:search_type", wrap(groupCreate(a)))
	app.Post("/v2/search/groups/:group_id/add/:tag", wrap(groupAdd(a)))
	app.Post("/v2/search/groups/:group_id/remove/:tag", wrap(groupRemove(a)))
	app.Get("/v2/search/groups/:group_id", wrap(groupGet(a)))
	app.Get("/v2/search/groups/:user_id/list", wrap(groupList(a)))
	app.Delete("/v2/search/groups/:group_id", wrap(groupDelete(a)))

	app.Get("/v2/link/server/:server_id/clan/list", wrap(serverroutes.GetServerClansBasic(a)))

	app.Get("/v2/legends/players/day/:day", legendStatsDay(a))
	app.Get("/v2/legends/players/season/:season", legendStatsSeason(a))
	app.Get("/v2/legends/guild-stats", guildStats(a))
	app.Get("/v2/legends/daily-tracking", dailyTracking(a))

	app.Get("/v2/public-config", publicMobileConfig(a))
	app.Post("/v2/initialization", wrap(mobileInitialization(a)))

	app.Post("/v2/roster", wrap(createRoster(a)))
	app.Get("/v2/roster/missing-members", getMissingMembers(a))
	app.Patch("/v2/roster/:roster_id", wrap(updateRoster(a)))
	app.Get("/v2/roster/:roster_id", getRoster(a))
	app.Delete("/v2/roster/:roster_id", wrap(deleteRoster(a)))
	app.Delete("/v2/roster/:roster_id/members/:player_tag", wrap(removeRosterMember(a)))
	app.Post("/v2/roster/refresh", wrap(refreshRosters(a)))
	app.Post("/v2/roster/:roster_id/clone", wrap(cloneRoster(a)))
	app.Get("/v2/roster/:server_id/list", listRosters(a))
	app.Post("/v2/roster-group", wrap(createRosterGroup(a)))
	app.Get("/v2/roster-group/list", listRosterGroups(a))
	app.Get("/v2/roster-group/:group_id", getRosterGroup(a))
	app.Patch("/v2/roster-group/:group_id", wrap(updateRosterGroup(a)))
	app.Delete("/v2/roster-group/:group_id", wrap(deleteRosterGroup(a)))
	app.Post("/v2/roster-signup-category", wrap(createRosterSignupCategory(a)))
	app.Get("/v2/roster-signup-category/list", wrap(listRosterSignupCategories(a)))
	app.Patch("/v2/roster-signup-category/:custom_id", wrap(updateRosterSignupCategory(a)))
	app.Delete("/v2/roster-signup-category/:custom_id", wrap(deleteRosterSignupCategory(a)))
	app.Post("/v2/roster/:roster_id/members", wrap(manageRosterMembers(a)))
	app.Patch("/v2/roster/:roster_id/members/:member_tag", wrap(updateRosterMember(a)))
	app.Post("/v2/roster/:roster_id/members/:member_tag/refresh", wrap(refreshRosterMember(a)))
	app.Post("/v2/roster-automation", wrap(createRosterAutomation(a)))
	app.Get("/v2/roster-automation/list", wrap(listRosterAutomation(a)))
	app.Patch("/v2/roster-automation/:automation_id", wrap(updateRosterAutomation(a)))
	app.Delete("/v2/roster-automation/:automation_id", wrap(deleteRosterAutomation(a)))
	app.Get("/v2/roster/server/:server_id/members", getServerClanMembers(a))
	app.Post("/v2/roster-token", wrap(generateRosterToken(a)))
	app.Get("/v2/server/:server_id/discord-channels", wrap(serverroutes.GetDiscordChannels(a)))
	app.Get("/v2/server/:server_id/discord-test", wrap(serverroutes.TestDiscordAPI(a)))

	app.Get("/v2/server/:server_id/settings", wrap(serverroutes.GetServerSettings(a)))
	app.Get("/v2/server/:server_id/clan/:clan_tag/settings", wrap(serverroutes.GetServerClanSettings(a)))
	app.Put("/v2/server/:server_id/embed-color/:hex_code", wrap(serverroutes.PutEmbedColor(a)))
	app.Patch("/v2/server/:server_id/settings", wrap(serverroutes.PatchServerSettings(a)))
	app.Get("/v2/server/:server_id/logs", wrap(serverroutes.GetServerLogs(a)))
	app.Put("/v2/server/:server_id/logs", wrap(serverroutes.UpdateServerLogs(a)))
	app.Patch("/v2/server/:server_id/logs/:log_type", wrap(serverroutes.PatchServerLogType(a)))
	app.Get("/v2/server/:server_id/clans-basic", wrap(serverroutes.GetServerClansBasic(a)))
	app.Get("/v2/server/:server_id/channels", wrap(serverroutes.ServerChannels(a)))
	app.Get("/v2/server/:server_id/threads", wrap(serverroutes.ServerThreads(a)))
	app.Get("/v2/server/:server_id/clan-logs", wrap(serverroutes.GetAllClanLogs(a)))
	app.Put("/v2/server/:server_id/clan/:clan_tag/logs", wrap(serverroutes.PutClanLogs(a)))
	app.Delete("/v2/server/:server_id/clan/:clan_tag/logs", wrap(serverroutes.DeleteClanLogs(a)))
	app.Get("/v2/server/:server_id/reminders", wrap(serverroutes.GetServerReminders(a)))
	app.Post("/v2/server/:server_id/reminders", wrap(serverroutes.CreateReminder(a)))
	app.Put("/v2/server/:server_id/reminders/:reminder_id", wrap(serverroutes.UpdateReminder(a)))
	app.Delete("/v2/server/:server_id/reminders/:reminder_id", wrap(serverroutes.DeleteReminder(a)))
	app.Get("/v2/server/:server_id/autoboards", wrap(serverroutes.GetAutoboards(a)))
	app.Post("/v2/server/:server_id/autoboards", wrap(serverroutes.CreateAutoboard(a)))
	app.Patch("/v2/server/:server_id/autoboards/:autoboard_id", wrap(serverroutes.UpdateAutoboard(a)))
	app.Delete("/v2/server/:server_id/autoboards/:autoboard_id", wrap(serverroutes.DeleteAutoboard(a)))
	app.Get("/v2/server/:server_id/links", wrap(serverroutes.GetLinks(a)))
	app.Delete("/v2/server/:server_id/links/:user_discord_id/:player_tag", wrap(serverroutes.DeleteLink(a)))
	app.Post("/v2/server/:server_id/links/bulk-unlink", wrap(serverroutes.BulkUnlink(a)))
	app.Get("/v2/server/:server_id/clans", wrap(serverroutes.GetServerClans(a)))
	app.Patch("/v2/server/:server_id/clan/:clan_tag/settings", wrap(serverroutes.PatchClanSettings(a)))
	app.Post("/v2/server/:server_id/clans", wrap(serverroutes.AddServerClan(a)))
	app.Delete("/v2/server/:server_id/clans/:clan_tag", wrap(serverroutes.RemoveServerClan(a)))
	app.Delete("/v2/server/:server_id/clan/:clan_tag", wrap(serverroutes.RemoveServerClan(a)))
	app.Get("/v2/server/:server_id/roles/:role_type", wrap(serverroutes.ListRoles(a)))
	app.Post("/v2/server/:server_id/roles/:role_type", wrap(serverroutes.CreateRole(a)))
	app.Delete("/v2/server/:server_id/roles/:role_type/:role_id", wrap(serverroutes.DeleteRole(a)))
	app.Get("/v2/server/:server_id/discord-roles", wrap(serverroutes.DiscordRoles(a)))
	app.Get("/v2/server/:server_id/role-settings", wrap(serverroutes.GetRoleSettings(a)))
	app.Patch("/v2/server/:server_id/role-settings", wrap(serverroutes.PatchRoleSettings(a)))
	app.Get("/v2/server/:server_id/all-roles", wrap(serverroutes.GetAllRoles(a)))
	app.Get("/v2/server/:server_id/family-roles", wrap(serverroutes.GetFamilyRoles(a)))
	app.Post("/v2/server/:server_id/family-roles", wrap(serverroutes.AddFamilyRole(a)))
	app.Delete("/v2/server/:server_id/family-roles/:role_type/:role_id", wrap(serverroutes.RemoveFamilyRole(a)))
	app.Get("/v2/server/:server_id/strikes", wrap(serverroutes.GetStrikes(a)))
	app.Post("/v2/server/:server_id/strikes/:player_tag", wrap(serverroutes.AddStrike(a)))
	app.Delete("/v2/server/:server_id/strikes/:strike_id", wrap(serverroutes.DeleteStrike(a)))
	app.Get("/v2/server/:server_id/strikes/player/:player_tag/summary", wrap(serverroutes.StrikeSummary(a)))
	app.Get("/v2/server/:server_id/bans", wrap(serverroutes.GetBans(a)))
	app.Post("/v2/server/:server_id/bans/:player_tag", wrap(serverroutes.AddBan(a)))
	app.Delete("/v2/server/:server_id/bans/:player_tag", wrap(serverroutes.RemoveBan(a)))
	app.Get("/v2/server/:server_id/countdowns", wrap(serverroutes.GetServerCountdowns(a)))

	app.Get("/v2/server/:server_id/panel", wrap(serverroutes.GetServerPanel(a)))
	app.Put("/v2/server/:server_id/panel", wrap(serverroutes.UpdateServerPanel(a)))

	app.Get("/v2/server/:server_id/tickets", wrap(serverroutes.GetTicketPanels(a)))
	app.Post("/v2/server/:server_id/tickets", wrap(serverroutes.CreateTicketPanel(a)))
	app.Delete("/v2/server/:server_id/tickets/:panel_name", wrap(serverroutes.DeleteTicketPanel(a)))
	app.Post("/v2/server/:server_id/tickets/:panel_name/buttons", wrap(serverroutes.CreateTicketButton(a)))
	app.Delete("/v2/server/:server_id/tickets/:panel_name/buttons/:custom_id", wrap(serverroutes.DeleteTicketButton(a)))
	app.Patch("/v2/server/:server_id/tickets/:panel_name/buttons/:custom_id", wrap(serverroutes.UpdateTicketButtonAppearance(a)))
	app.Get("/v2/server/:server_id/tickets/open", wrap(serverroutes.GetOpenTickets(a)))
	app.Put("/v2/server/:server_id/tickets/:panel_name", wrap(serverroutes.UpdateTicketPanel(a)))
	app.Put("/v2/server/:server_id/tickets/:panel_name/buttons/:custom_id", wrap(serverroutes.UpdateTicketButtonSettings(a)))
	app.Put("/v2/server/:server_id/tickets/:panel_name/approve-messages", wrap(serverroutes.UpdateTicketApproveMessages(a)))
	app.Put("/v2/server/:server_id/tickets/open/:channel_id/status", wrap(serverroutes.UpdateOpenTicketStatus(a)))
	app.Put("/v2/server/:server_id/tickets/open/:channel_id/clan", wrap(serverroutes.UpdateOpenTicketClan(a)))
	app.Delete("/v2/server/:server_id/tickets/open/:channel_id", wrap(serverroutes.DeleteOpenTicket(a)))
	app.Get("/v2/server/:server_id/embeds", wrap(serverroutes.GetServerEmbeds(a)))
	app.Post("/v2/server/:server_id/embeds", wrap(serverroutes.CreateServerEmbed(a)))
	app.Put("/v2/server/:server_id/embeds/:embed_name", wrap(serverroutes.UpdateServerEmbed(a)))
	app.Delete("/v2/server/:server_id/embeds/:embed_name", wrap(serverroutes.DeleteServerEmbed(a)))

	app.Get("/v2/server/:server_id/giveaways", wrap(serverroutes.GetServerGiveaways(a)))
	app.Get("/v2/server/:server_id/giveaways/:giveaway_id", wrap(serverroutes.GetServerGiveaway(a)))
	app.Post("/v2/server/:server_id/giveaways", wrap(serverroutes.CreateServerGiveaway(a)))
	app.Put("/v2/server/:server_id/giveaways/:giveaway_id", wrap(serverroutes.UpdateServerGiveaway(a)))
	app.Delete("/v2/server/:server_id/giveaways/:giveaway_id", wrap(serverroutes.DeleteServerGiveaway(a)))
	app.Get("/v2/server/:server_id/giveaways/:giveaway_id/entries", wrap(serverroutes.GetGiveawayEntries(a)))
	app.Post("/v2/server/:server_id/giveaways/:giveaway_id/reroll", wrap(serverroutes.RerollGiveawayWinners(a)))

	app.Get("/v2/server/:server_id/leaderboards", serverroutes.GetServerLeaderboards(a))
	app.Get("/v2/server/:server_id/leaderboards/war-performance", serverroutes.GetServerWarLeaderboard(a))
	app.Get("/v2/server/:server_id/leaderboards/donations", serverroutes.GetServerDonationsLeaderboard(a))
	app.Get("/v2/server/:server_id/leaderboards/capital-raids", serverroutes.GetServerCapitalRaidsLeaderboard(a))
	app.Get("/v2/server/:server_id/leaderboards/legends", serverroutes.GetServerLegendsLeaderboard(a))
	app.Get("/v2/server/:server_id/leaderboards/clan-games", serverroutes.GetServerClanGamesLeaderboard(a))
	app.Get("/v2/server/:server_id/leaderboards/activity", serverroutes.GetServerActivityLeaderboard(a))
	app.Get("/v2/server/:server_id/leaderboards/looting", serverroutes.GetServerLootingLeaderboard(a))
	app.Get("/v2/server/:server_id/clan/:clan_tag/countdowns", wrap(serverroutes.GetClanCountdowns(a)))
	app.Post("/v2/server/:server_id/countdowns", wrap(serverroutes.EnableCountdown(a)))
	app.Delete("/v2/server/:server_id/countdowns", wrap(serverroutes.DisableCountdown(a)))

	app.Get("/v2/categories", listCategories(a))
	app.Get("/v2/static/categories", listCategories(a))
	app.Get("/v2/static/app-bundle", appStaticDataBundle(a))
	app.Get("/v2/static/app-translations", appStaticTranslations(a))
	app.Get("/v2/:category/names", categoryNames(a))
	app.Get("/v2/static/:category/names", categoryNames(a))
	app.Get("/v2/:category/:item_id_or_name/maxlevel", maxLevel(a))
	app.Get("/v2/static/:category/:item_id_or_name/maxlevel", maxLevel(a))
	app.Get("/v2/:category/:item_id_or_name", categoryItem(a))
	app.Get("/v2/static/:category/:item_id_or_name", categoryItem(a))
	app.Get("/v2/:category", categoryItems(a))
	app.Get("/v2/static/:category", categoryItems(a))

	app.Post("/v2/players/location", playersLocation(a))
	app.Post("/v2/players/sorted/:attribute", playersSorted(a))
	app.Post("/v2/players/summary/:season/top", playersSummaryTop(a))
	app.Post("/v2/players/extended", playersExtended(a))
	app.Post("/v2/players/legend-days", playersLegendDays(a))
	app.Post("/v2/players/legend_rankings", playersLegendRankings(a))
	app.Post("/v2/players", playersBasic(a))
	app.Get("/v2/player/:player_tag/extended", playerExtendedSingle(a))

	app.Get("/v2/war/:clan_tag/previous", previousWars(a))
	app.Get("/v2/cwl/:clan_tag/ranking-history", cwlRankingHistory(a))
	app.Get("/v2/cwl/league-thresholds", cwlThresholds)
	app.Get("/v2/war/clan/stats", clanStats(a))
	app.Get("/v2/war/stats", clanStats(a))
	app.Post("/v2/war/war-summary", warSummaryBulk(a))
	app.Get("/v2/war/:clan_tag/war-summary", warSummarySingle(a))
	app.Post("/v2/war/players/warhits", playerWarhits(a))
	app.Post("/v2/war/clans/warhits", clanWarhits(a))

	app.Get("/v2/exports/war/cwl-summary", wrap(exportCWLSummary(a)))
	app.Post("/v2/exports/war/player-stats", wrap(exportPlayerWarStats(a)))

	app.Post("/v2/cdn/upload", wrap(uploadFileToCDN(a)))
}
