package v1

import (
	apptypes "github.com/ClashKingInc/ClashKingAPI/internal/utils"
	"github.com/gofiber/fiber/v2"
)

func Register(app *fiber.App, a apptypes.Deps) {
	app.Get("/assets", assets())
	app.Get("/json/:data_type", jsonData())
	app.Get("/v1/*", proxyGet())
	app.Post("/v1/*", proxyPost())
	app.Get("/bot/config", botConfig(a))
	app.Get("/permalink/:clan_tag", permalink(a))
	app.Post("/ck/bulk", ckBulkProxy(a))
	app.Get("/server-settings/:server_id", serverSettingsLegacy(a))
	app.Get("/boost-rate", superTroopBoostRate(a))
	app.Get("/global/counts", globalCounts(a))
	app.Get("/builderbaseleagues", builderBaseLeagues())
	app.Get("/list/townhalls", listTownhalls(a))
	app.Get("/list/seasons", listSeasons())
	app.Get("/legends/clan/:clan_tag/:date", legendsClan(a))
	app.Get("/legends/streaks", legendStreaks(a))
	app.Get("/legends/trophy-buckets", legendTrophyBuckets(a))
	app.Get("/legends/eos-winners", legendEOSWinners(a))
	app.Get("/ranking/live/legends", liveLegendRankings(a))
	app.Get("/ranking/legends/:player_tag", liveLegendRankingByPlayer(a))
	app.Get("/ranking/player-trophies/:location/:date", playerTrophiesRanking(a))
	app.Get("/ranking/player-builder/:location/:date", playerBuilderRanking(a))
	app.Get("/ranking/clan-trophies/:location/:date", clanTrophiesRanking(a))
	app.Get("/ranking/clan-builder/:location/:date", clanBuilderRanking(a))
	app.Get("/ranking/clan-capital/:location/:date", clanCapitalRanking(a))
	app.Get("/guild_links/:guild_id", guildLinks(a))
	app.Get("/shortner", shortener(a))
	app.Get("/shortlink", shortlink(a))
	app.Post("/discord_links", discordLinks(a))
	app.Get("/donations", donationsLegacy(a))
	app.Get("/activity", activityLegacy(a))
	app.Get("/clan-games", clanGamesLegacy(a))
	app.Get("/war-stats", warStatsLegacy(a))
	app.Get("/capital", capitalLegacy(a))

	app.Get("/capital/stats/district", districtStats(a))
	app.Get("/capital/stats/leagues", leagueStats(a))
	app.Get("/capital/:clan_tag", capitalLog(a))
	app.Post("/capital/bulk", capitalBulk(a))

	app.Get("/clan/:clan_tag/basic", clanBasic(a))
	app.Get("/clan/:clan_tag/join-leave", clanJoinLeave(a))
	app.Get("/clan/search", clanSearch(a))
	app.Get("/clan/:clan_tag/historical", clanHistorical(a))

	app.Get("/player/:player_tag/stats", playerStats(a))
	app.Get("/player/:player_tag/legends", playerLegends(a))
	app.Get("/player/:player_tag/historical/:season", playerHistorical(a))
	app.Get("/player/:player_tag/warhits", playerWarhits(a))
	app.Get("/player/:player_tag/raids", playerRaids(a))
	app.Get("/player/to-do", playerTodo(a))
	app.Get("/player/:player_tag/legend_rankings", playerLegendRankings(a))
	app.Get("/player/:player_tag/wartimer", playerWartimer(a))
	app.Get("/player/:player_tag/join-leave", playerJoinLeave(a))
	app.Get("/player/search/:name", playerSearchByName(a))
	app.Get("/player/full-search/:name", playerFullSearch(a))

	app.Get("/war/:clan_tag/previous", warPrevious(a))
	app.Get("/war/:clan_tag/previous/:end_time", warPreviousAtTime(a))
	app.Get("/war/:clan_tag/basic", warBasic(a))
	app.Get("/cwl/:clan_tag/group", cwlGroup(a))
	app.Get("/cwl/:clan_tag/:season", cwlSeason(a))
}
