package routes

import (
	serverroutes "github.com/ClashKingInc/ClashKingAPI/internal/routes/server"
	apptypes "github.com/ClashKingInc/ClashKingAPI/internal/utils"
	"github.com/gofiber/fiber/v2"
)

func Register(app *fiber.App, a apptypes.Deps, wrap func(fiber.Handler) fiber.Handler) {
	registerCompatibilityRoutes(app, a)

	userOrBot := func(handler fiber.Handler) fiber.Handler {
		return authUserOrBot(a, wrap, handler)
	}
	serverRead := func(handler fiber.Handler) fiber.Handler {
		return authServerRead(a, wrap, handler)
	}
	serverWrite := func(handler fiber.Handler) fiber.Handler {
		return authServerWrite(a, wrap, handler)
	}

	app.Get("/v2/clan/:clan_tag/badge", clanBadge(a))

	app.Get("/v2/links/:id", userOrBot(listAccounts(a)))
	app.Post("/v2/links/:id", userOrBot(addAccount(a)))
	app.Delete("/v2/links/:id/:playerTag", userOrBot(removeAccount(a)))
	app.Put("/v2/links/:id/order", userOrBot(reorderAccounts(a)))
	app.Get("/v2/links/:id/bookmarks", userOrBot(listBookmarks(a)))
	app.Post("/v2/links/:id/bookmarks", userOrBot(addBookmark(a)))
	app.Delete("/v2/links/:id/bookmarks/:type/:tag", userOrBot(deleteBookmark(a)))
	app.Put("/v2/links/:id/bookmarks/order", userOrBot(reorderBookmarks(a)))
	app.Get("/v2/links/:id/searches", userOrBot(listRecentSearches(a)))

	app.Get("/v2/guild-summary", guildSummary(a))
	app.Get("/v2/activity/guild-summary", guildSummary(a))

	app.Get("/v2/player/:player_tag/rankings", playerRankings(a))
	app.Get("/v2/player/:player_tag/battlelog/history", playerBattlelogHistory(a))
	app.Get("/v2/player/:player_tag/legends/:day/day", playerLegendsDayBattlelog(a))
	app.Get("/v2/player/:player_tag/legends/:season/season", playerLegendsSeasonBattlelog(a))
	app.Post("/v2/player/legends/:season/battlelog-stats", playersLegendsBattlelogStats(a))
	app.Get("/v2/player/:player_tag/ranked/:season/battlelog", playerRankedBattlelog(a))
	app.Get("/v2/player/:player_tag/ranked/:season/group", playerRankedGroup(a))
	app.Get("/v2/player/:player_tag/changes", playerChanges(a))
	app.Get("/v2/leaderboard/league/:league_tier_id", leaderboardLeague(a))
	app.Get("/v2/leaderboard/league/:league_tier_id/history/:date", leaderboardLeagueHistory(a))
	app.Get("/v2/leaderboard/townhalls/:townhall_level", leaderboardTownhalls(a))
	app.Get("/v2/leaderboard/townhalls/:townhall_level/history/:date", leaderboardTownhallsHistory(a))
	app.Get("/v2/leaderboard/:location_id/clan/donations", leaderboardClanDonations(a))
	app.Get("/v2/leaderboard/:location_id/clan/war-wins", leaderboardClanWarWins(a))
	app.Get("/v2/leaderboard/clan/win-streak", leaderboardClanWinStreak(a))
	app.Get("/v2/leaderboard/:league_tier_id/trophy-buckets", leaderboardTrophyBuckets(a))
	app.Get("/v2/global/cwl-leagues", globalCWLLeagues(a))
	app.Get("/v2/global/clan/locations", globalClanLocations(a))
	app.Get("/v2/global/townhalls", globalTownhalls(a))
	app.Get("/v2/global/builderhalls", globalBuilderhalls(a))
	app.Get("/v2/global/capital-leagues", globalCapitalLeagues(a))
	app.Get("/v2/global/leaguetiers", globalLeagueTiers(a))
	app.Get("/v2/clan/:clan_tag/changes", clanChanges(a))
	app.Get("/v2/clan/:clan_tag/rankings", clanRanking(a))
	app.Get("/v2/clan/:clan_tag/basic", clanBasic(a))
	app.Get("/v2/battlelogs/ranked/armies", battlelogsRankedArmies(a))
	app.Get("/v2/battlelogs/farming/armies", battlelogsFarmingArmies(a))
	app.Get("/v2/battlelogs/items/townhall/:townhall_level/usage", battlelogItemTownhallUsage(a))
	app.Get("/v2/battlelogs/items/townhall/:townhall_level/hitrate", battlelogItemTownhallHitrate(a))
	app.Get("/v2/battlelogs/items/league/:league_id/usage", battlelogItemLeagueUsage(a))
	app.Get("/v2/battlelogs/items/league/:league_id/hitrate", battlelogItemLeagueHitrate(a))
	app.Get("/v2/battlelogs/items/top200/usage", battlelogItemTop200Usage(a))
	app.Get("/v2/battlelogs/items/top200/hitrate", battlelogItemTop200Hitrate(a))

	app.Post("/v2/verify-email-code", verifyEmailCode(a))
	app.Post("/v2/auth/verify-email-code", verifyEmailCode(a))
	app.Get("/v2/me", wrap(currentUser(a)))
	app.Get("/v2/auth/me", wrap(currentUser(a)))
	app.Post("/v2/notifications/devices", wrap(registerNotificationDevice(a)))
	app.Delete("/v2/notifications/devices", wrap(disableNotificationDevice(a)))
	app.Get("/v2/notifications/preferences", wrap(getNotificationPreferences(a)))
	app.Put("/v2/notifications/preferences", wrap(putNotificationPreferences(a)))
	app.Post("/v2/discord", discordAuth(a))
	app.Post("/v2/auth/discord", discordAuth(a))
	app.Post("/v2/refresh", refreshToken(a))
	app.Post("/v2/auth/refresh", refreshToken(a))
	app.Post("/v2/register", register(a))
	app.Post("/v2/auth/register", register(a))
	app.Post("/v2/resend-verification", resendVerification(a))
	app.Post("/v2/auth/resend-verification", resendVerification(a))
	app.Post("/v2/email", emailLogin(a))
	app.Post("/v2/auth/email", emailLogin(a))
	app.Post("/v2/link-discord", wrap(linkDiscord(a)))
	app.Post("/v2/auth/link-discord", wrap(linkDiscord(a)))
	app.Post("/v2/link-email", wrap(linkEmail(a)))
	app.Post("/v2/auth/link-email", wrap(linkEmail(a)))
	app.Post("/v2/forgot-password", forgotPassword(a))
	app.Post("/v2/auth/forgot-password", forgotPassword(a))
	app.Post("/v2/reset-password", resetPassword(a))
	app.Post("/v2/auth/reset-password", resetPassword(a))

	app.Get("/v2/clan/:clan_tag/join-leave/stats", clanJoinLeaveStats(a))
	app.Get("/v2/clan/:clan_tag/join-leave", clanJoinLeave(a))

	app.Get("/v2/public", publicConfig(a))
	app.Get("/v2/config/public", publicConfig(a))

	app.Get("/v2/dates/seasons", seasons)
	app.Get("/v2/dates/raid-weekends", raidWeekends)
	app.Get("/v2/dates/current", currentDates)
	app.Get("/v2/dates/season-start-end", seasonStartEnd)
	app.Get("/v2/dates/season-raid-dates", seasonRaidDates)

	app.Get("/v2/guilds", wrap(getUserGuilds(a)))
	app.Get("/v2/guild/:server_id", wrap(getGuildDetails(a)))

	app.Get("/v2/internal/bot/info", userOrBot(botInfo(a)))

	app.Post("/v2/tracking/players/add", userOrBot(addTrackingPlayers(a)))
	app.Post("/v2/tracking/players/remove", userOrBot(removeTrackingPlayers(a)))
	app.Get("/v2/player/:player_tag/join-leave/totals", playerJoinLeaveTotals(a))
	app.Get("/v2/player/:player_tag/join-leave/shared", playerJoinLeaveShared(a))
	app.Get("/v2/player/:player_tag/join-leave", playerJoinLeave(a))

	app.Get("/v2/search/clan", searchClan(a))
	app.Get("/v2/search/:guild_id/banned-players", wrap(searchBannedPlayers(a)))
	app.Post("/v2/search/groups/create/:user_id/:name/:search_type", wrap(groupCreate(a)))
	app.Post("/v2/search/groups/:group_id/add/:tag", wrap(groupAdd(a)))
	app.Post("/v2/search/groups/:group_id/remove/:tag", wrap(groupRemove(a)))
	app.Get("/v2/search/groups/:group_id", wrap(groupGet(a)))
	app.Get("/v2/search/groups/:user_id/list", wrap(groupList(a)))
	app.Delete("/v2/search/groups/:group_id", wrap(groupDelete(a)))

	app.Get("/v2/link/server/:server_id/clan/list", serverRead(serverroutes.GetServerClansBasic(a)))

	app.Get("/v2/public-config", publicMobileConfig(a))
	app.Get("/v2/app/announcements/active", getActiveAppAnnouncement(a))
	app.Get("/v2/app/announcements/:id", getAppAnnouncement(a))
	app.Get("/v2/app/posts", listPublishedAppPosts(a))
	app.Get("/v2/app/config", getAppConfig(a))
	app.Post("/v2/initialization", wrap(mobileInitialization(a)))
	app.All("/proxy/v1/*", wrap(proxyForward(a, "/proxy/")))

	app.Post("/v2/roster", wrap(createRoster(a)))
	app.Get("/v2/roster/missing-members", getMissingMembers(a))
	app.Patch("/v2/roster/:roster_id", wrap(updateRoster(a)))
	app.Get("/v2/roster/:roster_id", getRoster(a))
	app.Delete("/v2/roster/:roster_id", wrap(deleteRoster(a)))
	app.Delete("/v2/roster/:roster_id/members/:player_tag", wrap(removeRosterMember(a)))
	app.Post("/v2/roster/refresh", wrap(refreshRosters(a)))
	app.Post("/v2/roster/:roster_id/clone", wrap(cloneRoster(a)))
	app.Get("/v2/roster/:server_id/list", serverRead(listRosters(a)))
	app.Post("/v2/roster-group", wrap(createRosterGroup(a)))
	app.Get("/v2/roster-group/list", listRosterGroups(a))
	app.Get("/v2/roster-group/:group_id", getRosterGroup(a))
	app.Patch("/v2/roster-group/:group_id", wrap(updateRosterGroup(a)))
	app.Delete("/v2/roster-group/:group_id", wrap(deleteRosterGroup(a)))
	app.Post("/v2/roster-signup-category", wrap(createRosterSignupCategory(a)))
	app.Get("/v2/roster-signup-category/list", wrap(listRosterSignupCategories(a)))
	app.Patch("/v2/roster-signup-category/:custom_id", wrap(updateRosterSignupCategory(a)))
	app.Delete("/v2/roster-signup-category/:custom_id", wrap(deleteRosterSignupCategory(a)))
	app.Post("/v2/roster/:roster_id/members", wrap(manageRosterMembers(a)))
	app.Patch("/v2/roster/:roster_id/members/:member_tag", wrap(updateRosterMember(a)))
	app.Post("/v2/roster/:roster_id/members/:member_tag/refresh", wrap(refreshRosterMember(a)))
	app.Post("/v2/roster-automation", wrap(createRosterAutomation(a)))
	app.Get("/v2/roster-automation/list", wrap(listRosterAutomation(a)))
	app.Patch("/v2/roster-automation/:automation_id", wrap(updateRosterAutomation(a)))
	app.Delete("/v2/roster-automation/:automation_id", wrap(deleteRosterAutomation(a)))
	app.Get("/v2/roster/server/:server_id/members", serverRead(getServerClanMembers(a)))
	app.Post("/v2/roster-token", wrap(generateRosterToken(a)))
	app.Get("/v2/server/:server_id/discord-channels", serverRead(serverroutes.GetDiscordChannels(a)))
	app.Get("/v2/server/:server_id/discord-test", serverRead(serverroutes.TestDiscordAPI(a)))

	app.Get("/v2/server/:server_id/settings", serverRead(serverroutes.GetServerSettings(a)))
	app.Get("/v2/server/:server_id/clan/:clan_tag/settings", serverRead(serverroutes.GetServerClanSettings(a)))
	app.Put("/v2/server/:server_id/embed-color/:hex_code", serverWrite(serverroutes.PutEmbedColor(a)))
	app.Patch("/v2/server/:server_id/settings", serverWrite(serverroutes.PatchServerSettings(a)))
	app.Get("/v2/server/:server_id/logs", serverRead(serverroutes.GetServerLogs(a)))
	app.Put("/v2/server/:server_id/logs", serverWrite(serverroutes.UpdateServerLogs(a)))
	app.Patch("/v2/server/:server_id/logs/:log_type", serverWrite(serverroutes.PatchServerLogType(a)))
	app.Get("/v2/server/:server_id/clans-basic", serverRead(serverroutes.GetServerClansBasic(a)))
	app.Get("/v2/server/:server_id/channels", serverRead(serverroutes.ServerChannels(a)))
	app.Get("/v2/server/:server_id/threads", serverRead(serverroutes.ServerThreads(a)))
	app.Get("/v2/server/:server_id/clan-logs", serverRead(serverroutes.GetAllClanLogs(a)))
	app.Put("/v2/server/:server_id/clan/:clan_tag/logs", serverWrite(serverroutes.PutClanLogs(a)))
	app.Delete("/v2/server/:server_id/clan/:clan_tag/logs", serverWrite(serverroutes.DeleteClanLogs(a)))
	app.Get("/v2/server/:server_id/reminders", serverRead(serverroutes.GetServerReminders(a)))
	app.Post("/v2/server/:server_id/reminders", serverWrite(serverroutes.CreateReminder(a)))
	app.Put("/v2/server/:server_id/reminders/:reminder_id", serverWrite(serverroutes.UpdateReminder(a)))
	app.Delete("/v2/server/:server_id/reminders/:reminder_id", serverWrite(serverroutes.DeleteReminder(a)))
	app.Get("/v2/server/:server_id/autoboards", serverRead(serverroutes.GetAutoboards(a)))
	app.Post("/v2/server/:server_id/autoboards", serverWrite(serverroutes.CreateAutoboard(a)))
	app.Patch("/v2/server/:server_id/autoboards/:autoboard_id", serverWrite(serverroutes.UpdateAutoboard(a)))
	app.Delete("/v2/server/:server_id/autoboards/:autoboard_id", serverWrite(serverroutes.DeleteAutoboard(a)))
	app.Get("/v2/server/:server_id/links", serverRead(serverroutes.GetLinks(a)))
	app.Delete("/v2/server/:server_id/links/:user_id/:player_tag", serverWrite(serverroutes.DeleteLink(a)))
	app.Post("/v2/server/:server_id/links/bulk-unlink", serverWrite(serverroutes.BulkUnlink(a)))
	app.Get("/v2/server/:server_id/clans", serverRead(serverroutes.GetServerClans(a)))
	app.Patch("/v2/server/:server_id/clan/:clan_tag/settings", serverWrite(serverroutes.PatchClanSettings(a)))
	app.Post("/v2/server/:server_id/clans", serverWrite(serverroutes.AddServerClan(a)))
	app.Delete("/v2/server/:server_id/clans/:clan_tag", serverWrite(serverroutes.RemoveServerClan(a)))
	app.Delete("/v2/server/:server_id/clan/:clan_tag", serverWrite(serverroutes.RemoveServerClan(a)))
	app.Get("/v2/server/:server_id/roles/:role_type", serverRead(serverroutes.ListRoles(a)))
	app.Post("/v2/server/:server_id/roles/:role_type", serverWrite(serverroutes.CreateRole(a)))
	app.Delete("/v2/server/:server_id/roles/:role_type/:role_id", serverWrite(serverroutes.DeleteRole(a)))
	app.Get("/v2/server/:server_id/discord-roles", serverRead(serverroutes.DiscordRoles(a)))
	app.Get("/v2/server/:server_id/role-settings", serverRead(serverroutes.GetRoleSettings(a)))
	app.Patch("/v2/server/:server_id/role-settings", serverWrite(serverroutes.PatchRoleSettings(a)))
	app.Get("/v2/server/:server_id/all-roles", serverRead(serverroutes.GetAllRoles(a)))
	app.Get("/v2/server/:server_id/family-roles", serverRead(serverroutes.GetFamilyRoles(a)))
	app.Post("/v2/server/:server_id/family-roles", serverWrite(serverroutes.AddFamilyRole(a)))
	app.Delete("/v2/server/:server_id/family-roles/:role_type/:role_id", serverWrite(serverroutes.RemoveFamilyRole(a)))
	app.Get("/v2/server/:server_id/strikes", serverRead(serverroutes.GetStrikes(a)))
	app.Post("/v2/server/:server_id/strikes/:player_tag", serverWrite(serverroutes.AddStrike(a)))
	app.Delete("/v2/server/:server_id/strikes/:strike_id", serverWrite(serverroutes.DeleteStrike(a)))
	app.Get("/v2/server/:server_id/strikes/player/:player_tag/summary", serverRead(serverroutes.StrikeSummary(a)))
	app.Get("/v2/server/:server_id/bans", serverRead(serverroutes.GetBans(a)))
	app.Post("/v2/server/:server_id/bans/:player_tag", serverWrite(serverroutes.AddBan(a)))
	app.Delete("/v2/server/:server_id/bans/:player_tag", serverWrite(serverroutes.RemoveBan(a)))
	app.Get("/v2/server/:server_id/countdowns", serverRead(serverroutes.GetServerCountdowns(a)))

	app.Get("/v2/server/:server_id/panel", serverRead(serverroutes.GetServerPanel(a)))
	app.Put("/v2/server/:server_id/panel", serverWrite(serverroutes.UpdateServerPanel(a)))

	app.Get("/v2/server/:server_id/tickets", serverRead(serverroutes.GetTicketPanels(a)))
	app.Post("/v2/server/:server_id/tickets", serverWrite(serverroutes.CreateTicketPanel(a)))
	app.Delete("/v2/server/:server_id/tickets/:panel_name", serverWrite(serverroutes.DeleteTicketPanel(a)))
	app.Post("/v2/server/:server_id/tickets/:panel_name/buttons", serverWrite(serverroutes.CreateTicketButton(a)))
	app.Delete("/v2/server/:server_id/tickets/:panel_name/buttons/:custom_id", serverWrite(serverroutes.DeleteTicketButton(a)))
	app.Patch("/v2/server/:server_id/tickets/:panel_name/buttons/:custom_id", serverWrite(serverroutes.UpdateTicketButtonAppearance(a)))
	app.Get("/v2/server/:server_id/tickets/open", serverRead(serverroutes.GetOpenTickets(a)))
	app.Put("/v2/server/:server_id/tickets/:panel_name", serverWrite(serverroutes.UpdateTicketPanel(a)))
	app.Put("/v2/server/:server_id/tickets/:panel_name/buttons/:custom_id", serverWrite(serverroutes.UpdateTicketButtonSettings(a)))
	app.Put("/v2/server/:server_id/tickets/:panel_name/approve-messages", serverWrite(serverroutes.UpdateTicketApproveMessages(a)))
	app.Put("/v2/server/:server_id/tickets/open/:channel_id/status", serverWrite(serverroutes.UpdateOpenTicketStatus(a)))
	app.Put("/v2/server/:server_id/tickets/open/:channel_id/clan", serverWrite(serverroutes.UpdateOpenTicketClan(a)))
	app.Delete("/v2/server/:server_id/tickets/open/:channel_id", serverWrite(serverroutes.DeleteOpenTicket(a)))
	app.Get("/v2/server/:server_id/embeds", serverRead(serverroutes.GetServerEmbeds(a)))
	app.Post("/v2/server/:server_id/embeds", serverWrite(serverroutes.CreateServerEmbed(a)))
	app.Put("/v2/server/:server_id/embeds/:embed_name", serverWrite(serverroutes.UpdateServerEmbed(a)))
	app.Delete("/v2/server/:server_id/embeds/:embed_name", serverWrite(serverroutes.DeleteServerEmbed(a)))

	app.Get("/v2/server/:server_id/giveaways", serverRead(serverroutes.GetServerGiveaways(a)))
	app.Get("/v2/server/:server_id/giveaways/:giveaway_id", serverRead(serverroutes.GetServerGiveaway(a)))
	app.Post("/v2/server/:server_id/giveaways", serverWrite(serverroutes.CreateServerGiveaway(a)))
	app.Put("/v2/server/:server_id/giveaways/:giveaway_id", serverWrite(serverroutes.UpdateServerGiveaway(a)))
	app.Delete("/v2/server/:server_id/giveaways/:giveaway_id", serverWrite(serverroutes.DeleteServerGiveaway(a)))
	app.Get("/v2/server/:server_id/giveaways/:giveaway_id/entries", serverRead(serverroutes.GetGiveawayEntries(a)))
	app.Post("/v2/server/:server_id/giveaways/:giveaway_id/reroll", serverWrite(serverroutes.RerollGiveawayWinners(a)))

	app.Get("/v2/server/:server_id/leaderboards", serverRead(serverroutes.GetServerLeaderboards(a)))
	app.Get("/v2/server/:server_id/leaderboards/war-performance", serverRead(serverroutes.GetServerWarLeaderboard(a)))
	app.Get("/v2/server/:server_id/leaderboards/donations", serverRead(serverroutes.GetServerDonationsLeaderboard(a)))
	app.Get("/v2/server/:server_id/leaderboards/capital-raids", serverRead(serverroutes.GetServerCapitalRaidsLeaderboard(a)))
	app.Get("/v2/server/:server_id/leaderboards/legends", serverRead(serverroutes.GetServerLegendsLeaderboard(a)))
	app.Get("/v2/server/:server_id/leaderboards/clan-games", serverRead(serverroutes.GetServerClanGamesLeaderboard(a)))
	app.Get("/v2/server/:server_id/leaderboards/activity", serverRead(serverroutes.GetServerActivityLeaderboard(a)))
	app.Get("/v2/server/:server_id/leaderboards/looting", serverRead(serverroutes.GetServerLootingLeaderboard(a)))
	app.Get("/v2/server/:server_id/clan/:clan_tag/countdowns", serverRead(serverroutes.GetClanCountdowns(a)))
	app.Post("/v2/server/:server_id/countdowns", serverWrite(serverroutes.EnableCountdown(a)))
	app.Delete("/v2/server/:server_id/countdowns", serverWrite(serverroutes.DisableCountdown(a)))

	app.Get("/v2/war/:clan_tag/previous", previousWars(a))
	app.Get("/v2/clan/:clan_tag/wars", clanWars(a))
	app.Get("/v2/cwl/:clan_tag/ranking-history", cwlRankingHistory(a))
	app.Get("/v2/cwl/league-thresholds", cwlThresholds)
	app.Get("/v2/war/clan/stats", clanStats(a))
	app.Get("/v2/war/stats", clanStats(a))
	app.Post("/v2/war/war-summary", warSummaryBulk(a))
	app.Get("/v2/war/:clan_tag/war-summary", warSummarySingle(a))
	app.Post("/v2/war/players/warhits", playerWarhits(a))
	app.Post("/v2/war/clans/warhits", clanWarhits(a))
	app.Get("/v2/player/:player_tag/war/attacks", playerWarAttacks(a))
	app.Get("/v2/player/:player_tag/war/stats", playerWarStats(a))
	app.Get("/v2/global/war/townhall/:townhall_level/hitrate/weekly", warTownhallWeeklyHitrate(a))
	app.Get("/v2/global/war/completed/daily", warCompletedDaily(a))

	app.Get("/v2/exports/war/cwl-summary", wrap(exportCWLSummary(a)))
	app.Post("/v2/exports/war/player-stats", wrap(exportPlayerWarStats(a)))

	app.Post("/v2/cdn/upload", wrap(uploadFileToCDN(a)))
}

func registerCompatibilityRoutes(app *fiber.App, a apptypes.Deps) {
	app.Get("/global/counts", globalCounts(a))
	app.Get("/global/war/townhall/:townhall_level/hitrate/weekly", warTownhallWeeklyHitrate(a))
	app.Get("/global/war/completed/daily", warCompletedDaily(a))
	app.Get("/builderbaseleagues", builderBaseLeagues())
	app.Get("/list/townhalls", listTownhalls(a))
	app.Get("/list/seasons", listSeasons())
	app.Get("/v2/ranking/player-trophies/:location/:date", playerTrophiesRanking(a))
	app.Get("/v2/ranking/player-builder/:location/:date", playerBuilderRanking(a))
	app.Get("/v2/ranking/clan-trophies/:location/:date", clanTrophiesRanking(a))
	app.Get("/v2/ranking/clan-builder/:location/:date", clanBuilderRanking(a))
	app.Get("/v2/ranking/clan-capital/:location/:date", clanCapitalRanking(a))

	app.Get("/war/:clanTag/previous", warPreviousAtTime(a))
	app.Get("/war/:clanTag/basic", warBasic(a))
	app.Get("/cwl/:clanTag/group", cwlGroup(a))
	app.Get("/cwl/:clanTag/:season", cwlSeason(a))
}
