name: Production API Image Builder

on:
  push:
    branches:
      - master  # Trigger only on push to master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}  # Automatically checkout the triggering branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set environment variables
        run: |
          echo "APP_ENV=production" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/clashkinginc/clashkingapi" >> $GITHUB_ENV

      - name: Sanitize branch name
        id: sanitize
        run: echo "SANITIZED_BRANCH=$(echo '${{ github.event.pull_request.head.ref }}' | sed 's/[^a-zA-Z0-9_.-]/-/g')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: APP_ENV=${{ env.APP_ENV }}

      - name: Verify pushed images
        run: |
          echo "Pushed image: ${{ env.IMAGE_NAME }}:latest"
          echo "Pushed image: ${{ env.IMAGE_NAME }}:${{ github.sha }}"
